final Map<String, List<String>> pronunciationExceptions = {
  // Kendaraan
  "mobil": ["mo", "bil"],
  "motor": ["mo", "tor"],
  "sepeda": ["se", "pe", "da"],
  "kereta": ["ke", "re", "ta"],
  "pesawat": ["pe", "sa", "wat"],
  "kapal": ["ka", "pal"],
  "bus": ["bus"],
  "truk": ["truk"],
  "ambulan": ["am", "bu", "lan"],

  // Peralatan Rumah Tangga
  "televisi": ["te", "le", "vi", "si"],
  "microwave": ["mi", "cro", "wave"],
  "kulkas": ["kul", "kas"],
  "kompor": ["kom", "por"],
  "oven": ["o", "ven"],
  "kipas": ["ki", "pas"],
  "lampu": ["lam", "pu"],
  "remot": ["re", "mot"],
  "telepon": ["te", "le", "pon"],
  "keyboard": ["key", "board"],
  "laptop": ["lap", "top"],
  "pemanggang": ["pe", "mang", "gang"],
  "wastafel": ["was", "ta", "fel"],
  "mesin cuci": ["me", "sin", "cu", "ci"],
  "botol": ["bo", "tol"],

  // Makanan dan Minuman
  "pizza": ["pit", "za"],
  "donat": ["do", "nat"],
  "sandwich": ["sand", "wich"],
  "apel": ["a", "pel"],
  "pisang": ["pi", "sang"],
  "wortel": ["wor", "tel"],
  "brokoli": ["bro", "ko", "li"],
  "telur": ["te", "lur"],
  "ayam": ["a", "yam"],
  "susu": ["su", "su"],
  "roti": ["ro", "ti"],
  "burger": ["bur", "ger"],
  "es krim": ["es", "krim"],

  // Binatang
  "anjing": ["an", "jing"],
  "kucing": ["ku", "cing"],
  "burung": ["bu", "rung"],
  "jerapah": ["je", "ra", "pah"],
  "zebra": ["ze", "bra"],
  "sapi": ["sa", "pi"],
  "kuda": ["ku", "da"],
  "gajah": ["ga", "jah"],
  "monyet": ["mo", "nyet"],
  "ikan": ["i", "kan"],

  // Objek Sekitar
  "meja": ["me", "ja"],
  "kursi": ["kur", "si"],
  "payung": ["pa", "yung"],
  "jendela": ["jen", "de", "la"],
  "pintu": ["pin", "tu"],
  "jam": ["jam"],
  "cermin": ["cer", "min"],
  "bantal": ["ban", "tal"],
  "boneka": ["bo", "ne", "ka"],
  "boneka beruang": ["bo", "ne", "ka", "be", "ru", "ang"],
  "pengering rambut": ["pe", "nge", "ring", "ram", "but"],
  "tas punggung": ["tas", "pung", "gung"],
  "tas tangan": ["tas", "tang", "an"],

  // Lalu Lintas
  "lampu lalu lintas": ["lam", "pu", "la", "lu", "lin", "tas"],
  "zebra cross": ["zebra", "cros"],
  "rambu lalu lintas": ["ram", "bu", "la", "lu", "lin", "tas"],
  "trotoar": ["tro", "to", "ar"],

  // Lainnya
  "bola": ["bo", "la"],
  "rak": ["rak"],
  "tas": ["tas"],
  "sepatu": ["se", "pa", "tu"],
  "topi": ["to", "pi"],
  "kacamata": ["ka", "ca", "ma", "ta"],
  "frisbi": ["fris", "bi"],
  "orang": ["o", "rang"],
  "tanaman pot": ["ta", "na", "man", "pot"],
};
