// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF3KQ1YUbRXDaBqKP7MmejK5QvQgYaxo0',
    appId: '1:313504734487:web:4ae40f0969581d6a83eb52',
    messagingSenderId: '313504734487',
    projectId: 'bicaraku-a81ab',
    authDomain: 'bicaraku-a81ab.firebaseapp.com',
    storageBucket: 'bicaraku-a81ab.firebasestorage.app',
    measurementId: 'G-YYRCSCQ5MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiTUbmuGBeQOj3YHRC1b-t6t5TnmphQEk',
    appId: '1:313504734487:android:afd3e7caa55ea79183eb52',
    messagingSenderId: '313504734487',
    projectId: 'bicaraku-a81ab',
    storageBucket: 'bicaraku-a81ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy8RepgcMHBDovP88r0L3J9WPqM23L_A0',
    appId: '1:313504734487:ios:64c4125c0f56c3d283eb52',
    messagingSenderId: '313504734487',
    projectId: 'bicaraku-a81ab',
    storageBucket: 'bicaraku-a81ab.firebasestorage.app',
    androidClientId: '313504734487-6njiehjrop162b819vbt455bcoo7otjh.apps.googleusercontent.com',
    iosClientId: '313504734487-1m6k3qpek0m1ecb8saptmsntutepe9it.apps.googleusercontent.com',
    iosBundleId: 'com.bicaraku.bicaraku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy8RepgcMHBDovP88r0L3J9WPqM23L_A0',
    appId: '1:313504734487:ios:64c4125c0f56c3d283eb52',
    messagingSenderId: '313504734487',
    projectId: 'bicaraku-a81ab',
    storageBucket: 'bicaraku-a81ab.firebasestorage.app',
    androidClientId: '313504734487-6njiehjrop162b819vbt455bcoo7otjh.apps.googleusercontent.com',
    iosClientId: '313504734487-1m6k3qpek0m1ecb8saptmsntutepe9it.apps.googleusercontent.com',
    iosBundleId: 'com.bicaraku.bicaraku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF3KQ1YUbRXDaBqKP7MmejK5QvQgYaxo0',
    appId: '1:313504734487:web:ab0cea56c32ac1bd83eb52',
    messagingSenderId: '313504734487',
    projectId: 'bicaraku-a81ab',
    authDomain: 'bicaraku-a81ab.firebaseapp.com',
    storageBucket: 'bicaraku-a81ab.firebasestorage.app',
    measurementId: 'G-8JB0FN6DGN',
  );
}
